title: Abi Goes Tallinn 2016
email: info@a8e.fi
description: >
  Tähän kuvaus sivustosta
baseurl: ""
url: "http://abigoestallinn.fi"

# Build settings
markdown: kramdown

# Navigation
navigation:
  main:
    links:
      - title: Matkainfo
        href: /matkainfo/
        dropdown:
          - title: FAQ
            href: /matka-info/faq/
      - title: Tallinna-info
        href: /tallinna-info/
        dropdown:
          - title: Kaupunki
            href: /tallinna-info/kaupunki/
          - title: Ostokset
            href: /tallinna-info/ostokset/
          - title: Ruoka ja juoma
            href: /tallinna-info/ruoka-ja-juoma/
      - title: Aikataulu 2016
        href: /aikataulu/
      - title: Turvainfo
        href: /turvainfo/
        dropdown:
          - title: Info vanhemmille
            href: /turvainfo/info-vanhemmille/
          - title: Yhteystiedot
            href: /yhteystiedot/
      - title: Yhteistyökumppanit
        href: /yhteistyokumppanit/
      - title: Yhteystiedot
        href: /yhteystiedot/
